name: "Build and publish site"
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: |
        SITE=$(nix-build --no-out-link -A packages.x86_64-linux.site)
        # This is broken because of weird TLS stuff on www-users.cs.umn.edu;
        # see UMN CSE-IT ticket #499458
        nix-shell --run "lychee $SITE/**/*.html" || true
        nix-shell --run "ghp-import -m \"Automatic update\" \"$SITE\""
        git push --force origin gh-pages:gh-pages
